import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReactQuery from "@/components/ReactQuery";
import { Providers } from "./providers";

const quciksand = localFont({
  src: [
    {
      path: "../public/fonts/Poppins-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "FullStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quciksand.className}>
        <noscript>
          Anda harus mengaktifkan JavaScript untuk menjalankan aplikasi ini
        </noscript>
        <ReactQuery><Providers> {children}</Providers></ReactQuery>
      </body>
    </html>
  );
}
